apiVersion: 1

datasources:
  - name: Postgres-Traffic
    type: postgres
    access: proxy
    url: postgres:5432
    database: traffic
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false